### ISSUE TITLE
XSharedPreferences don't work

### ISSUE THREAD

**Issue by a1e3cdc47c9eae132bd41ae1f5d0510d** [romracer/android_art#2]
I am trying to load my preferences using XSharedPreferences:

XSharedPreferences cfg; // Global var
// init zygote function
cfg = new XSharedPreferences("de.xxx.xxx"); // Package name
cfg.makeWorldReadable();
// loadPackage function
cfg.getBoolean("xxx_enabled", false); // Always returns false, even if config says true

Saving with: (mainactivity.java)
public void clickSwitch(View view) {
SharedPreferences prefs = PreferencesManager.getDefaultSharedPreferences(this);
SharedPreferences.Editor cfg = prefs.edit()
cfg.putBoolean("xxx_enabled", view.isEnabled());
}

I am using a LG-G3 with Resurecction Remix Rom.
SELinux-Status: Strict // Maybe thats it
Newest Xposed framework (14.05.15).

**Comment by romracer** [comment]
You should see "avc denied" messages in the kernel ring buffer if its SELinux related.  Can you type "dmesg" from an adb shell to print the ring buffer after having tried the process a couple of times?

**Comment by a1e3cdc47c9eae132bd41ae1f5d0510d** [comment]
It was SELinux related. after changing ot with the SELinuxModeChanger app it worked.
